@startuml class_example

/' the purpose if to demonstrate the new aliases and macroses
defined for the class diagram '/

!ifndef CLASSES
!include ../Templates/Classes.cuml
!endif

title Class  Diagram Example

/' standard syntax '/

abstract class AbstractClass {
    - {abstract} some_method() : int -> float
}

interface FooInterface {
    + some_other_method() : int -> float
}

class BarClass {
    - {static} some_class_attribute : int
    + some_instance_attribute : float
    - some_method() : int -> float # implemented
}

AbstractClass <|-- BarClass

FooInterface <|-- BarClass

enum States {
    OK
    NOK
    NAN
}

/' extended syntax '/

class Proto <<PROTOTYPE>> {
    - static_field(some_class_attribute) : int
    + some_instance_attribute : float
    - abstract(some_method) : int -> float
}

BarClass <-- Proto : < calls

class Mix <<MIXIN>> {
    + some_other_method() : int -> float
}

class Specific {
    - some_method() : int -> float # implemented
}

Proto <|-- Specific

Mix <|-- Specific

class Universal <<GENERIC>> {
    + some__method() : type A -> float
}

States <-- Universal : < uses

class Solo <<SINGLETON>> {
    static_field(class_attributes_only) : some_type
    static_method(class_methods_only) : some_type -> other_type
}

@enduml