!define STANDARDS_CHANGE_TYPES

!ifndef TABLES
!include ../Tables.cuml
!endif

enumeration(change_types) {
    primary(id)
    {field} name: varchar(20) UNIQUE NOT NULL
    !ifndef HIDE
        comment(types of hardware changes to journal)
    !endif
}