!define STANDARDS_PARTS

!ifndef TABLES
!include ../Templates/Tables.cuml
!endif

enumeration(parts) {
    primary(id)
    {field} foreign(material_id, materials, id)
    {field} foreign(construction_id, constructions, id)
    !ifndef HIDE
        comment(list of parts of standards)
    !endif
}