!$STANDARDS_CHANGE_TYPES = "v2"

!if (%not(%variable_exists($TABLES)))
    !include ../Tables2.cuml
!endif

$enumeration(change_types) {
    $primary(id)
    {field} name: varchar(20) UNIQUE NOT NULL
    !if $is_not_hide()
        $comment("types of hardware changes to journal")
    !endif
}