!define STANDARDS_MATERIAL_TYPES

!ifndef TABLES
!include ../Templates/Tables.cuml
!endif

enumeration(material_types) {
    primary(id)
    {field} name: varchar(20) UNIQUE NOT NULL
    !ifndef HIDE
        comment("material types, e.g. flourophore, etc.")
    !endif
}