!define STANDARDS_SERIALS

!ifndef TABLES
!include ../Tables.cuml
!endif

table(serials) {
    primary(id)
    {field} name: varchar(10) UNIQUE NOT NULL
    !ifndef HIDE
        is_active: bool NOT NULL DEFAULT FALSE
        calibration_id: smallint
        calibration_date: date NOT NULL
    !endif
    foreign(type_id,types,id)
    foreign(user_id,subjects.users,id)
    foreign(construction_id,constructions,id)
    !ifndef HIDE
        comment(main table for standards registration)
    !endif
}