!STANDARDS_PARTS = "v2"

!if (%not(%variable_exists($TABLES)))
    !include ../Tables2.cuml
!endif

$enumeration(parts) {
    $primary(id)
    $foreign(material_id, materials, id)
    $foreign(construction_id, constructions, id)
    !if $is_not_hide()
        $comment("list of parts of standards")
    !endif
}