!define STANDARDS_CHANGE_TYPES

!ifndef TABLES
!include ../Templates/Tables.cuml
!endif

enumeration(change_types) {
    {field} primary(id)
    {field} name: varchar(20) UNIQUE NOT NULL
    !ifndef HIDE
        {method} types of hardware changes to journal
    !endif
}