!$STANDARDS_MATERIAL_TYPES = "v2"

!if (%not(%variable_exists($TABLES)))
    !include ../Tables2.cuml
!endif

$enumeration(material_types) {
    $primary(id)
    {field} name: varchar(20) UNIQUE NOT NULL
    !if $is_not_hide()
        $comment("material types, e.g. flourophore, etc.")
    !endif
}