!define STANDARDS_CHANGES

!ifndef TABLES
!include ../Templates/Tables.cuml
!endif

table(changes) {
    primary(id)
    event_date: date NOT NULL
    foreign(standard_id, serials, id)
    foreign(change_id, change_types, id)
    !ifndef HIDE\
        {field} old_value: varchar(20)
        {field} new_value: varchar(20)
        comment(journal of hardware changes)
    !endif
}