!define STANDARDS_MATERIALS

!ifndef TABLES
!include ../Tables.cuml
!endif

enumeration(materials) {
    primary(id)
    {field} name: varchar(20) UNIQUE NOT NULL
    foreign(material_type_id, material_types, id)
    !ifndef HIDE
        {field} producer: varchar(20)
        {field} provider: varchar(20)
        {field} comment: varchar(255)
        {field} registration_path: varchar(255)
        comment(materials used as parts of standards)
    !endif
}