@startuml standards_constructions_view

title standards.constructions_view

!$STANDARDS_MATERIALS_VIEW = "v2"

!if (%not(%variable_exists($TABLES)))
    !include ../Tables2.cuml
!endif

!if $is_not_defined($STANDARDS_PARTS)
    !include ./standards_parts.iuml
!endif

!if $is_not_defined($STANDARDS_MATERIALS)
    !include ./standards_materials.iuml
!endif

$many(materials, parts, u)

!if $is_not_defined($STANDARDS_CONSTRUCTIONS)
    !include ./standards_constructions.iuml
!endif

$many(constructions, parts, r)

!if $is_not_defined($STANDARDS_MATERIAL_TYPES)
    !include ./standards_material_types.iuml
!endif

$many(material_types, materials, u)

$left_join(parts, constructions, j1, parts, "parts.construction_id = constructions.id")

$left_join(j1, materials, j2, $condition = "parts.material_id = materials.id")

$left_join(j2, material_types, j3, $condition = ", material_type.id = material_types.id")

$view(constructions_view) {
    {field} constructions.name AS construction: varchar(10) NOT NULL
    {field} constructions.comment AS description: varchar(255)
    {field} material_types.name AS part: varchar(20)
    {field} materials.name AS material_name: varchar(20)
    {field} materials.comment AS material_comment: varchar(255)
    {field} materials.producer /AS producer/: varchar(20)
    {field} materials.provider /AS provider/: varchar(20)
}

j3 <|-- constructions_view : SELECT

@enduml