!define SUBJECTS_USERS

!ifndef TABLES
!include ../Templates/Tables.cuml
!endif

table(users) {
    primary(id)
    {field} name: varchar(20) UNIQUE NOT NULL
    !ifndef HIDE
        {field} full_name: varchar(255)
        {field} address: varchar(255)
        {field} "e-mail": varchar(50)
        {field} phone: varchar(20)
        comment(companies as users)
    !endif
}