@startuml classes_stereotypes

!include ../../Classes2.cuml

$mixin_class(Mixin1)

$left_mixin_class(Mixin2)

$right_mixin_class(Mixin3)

$prototype_class(Proto)

$singleton_class(Single)

$generic_class(ABC)

@enduml