@startuml classes_attributes

!include ../../Classes2.cuml

class MyClass {
    # $abstract_method("VirtualMethod") : int -> None
    + $static_method("StaticMethod") : float -> str
}

MyClass : - $static_field(Accounts) : list(int)

@enduml