@startuml components_package

!include ../../Components2.cuml

$package(Name) {
    $file(SomeData)
}

$package(Long Name, Name2) {
    $file(SomeOtherData)
}

Name -- Name2 : same distribution

@enduml