@startuml plant_uml_components

!include ../../Components2.cuml

$library(plant_uml) {
    folder class_example
    
    folder components_example
    
    folder database_example
    
    folder Documentation
    
    $module(Classes.cuml)
    
    $module(Components.cuml)
    
    $module(Tables.cuml)
    
    $module(General.cuml)

    $module(Classes2.cuml)
    
    $module(Components2.cuml)
    
    $module(Tables2.cuml)
    
    $module(General2.cuml)
}

@enduml