@startuml tables_relations

!include ../../Tables2.cuml

$table(Organization) {
    $primary(id)
    {field} function: varchar(20)
}

$table(Buildings) {
    $primary(id)
    {field} address: varchar(255)
}

$table(Users) {
    $primary(id)
    {field} full_name: varchar(255)
    $small_unique_foreign(function_id, Organization, id)
    $foreign(office_id, Buildings, id)
}

$one(Organization, Users)

$many(Buildings, Users, 'u')

@enduml