@startuml tables_classes

!include ../../Tables.cuml

table(Users) {
    primary(id)
    {field} full_name: varchar(255)
}

Users : age : smallint

enumeration(Keys)

index(Users_index)

sequence('Users_pkey_counter')

query(Query1)

query(Query2, NamedQuery)

view(AllUsers)

@enduml