@startuml tables_unions

!include ../../Tables.cuml

query(Query1, Query1) {
    field1: some type
    field2: some type
    field3: some type
    comment(e.g. selection from some tables)
}

query(Query2, Query2) {
    field1: some type
    field2: some type
    field3: some type
    comment(e.g. selection from other tables)
}

query(Query3, Query3) {
    field1: some type
    field2: some type
    field3: some type
    comment(e.g. selection from yet other tables)
}

union(Query1, Query2, j1, Query1)

union(j1, Query3, j2)

view(Report) {
    field1: some type
    field2: some type
    field3: some type
    comment(ORDER BY field1)
}

j2 <|- Report : SELECT

@enduml